name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  manual_job:
    runs-on: ubuntu-latest
    steps:
      - name: Manual Run
        run: echo "Executing manual task for the ${{ github.event.inputs.environment }} environment!"  
