name: PR Check Workflow
on: 
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  pr_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
       
      - name: Branch Info
        run: echo "PR check running for branch: ${{ github.head_ref }}"
