name: Self Hosted Runner task
on: 
  workflow_dispatch:

jobs:
  self-hosted-job:
    runs-on: [self-hosted, my-linux-runner]
    steps:
      - name: Show runner info
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
      
      - name: Show working directory
        run: pwd 

      - name: Create file
        run: |
          echo "Hello from self-hosted runner" > test.txt

      - name: List files
        run: ls
