name: Run Real Tests in CI

on: 
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create a directory log and logs files
        run: |
          mkdir logs
          echo "This is fine" > logs/app.log
          echo "ERROR: something failed" >> logs/app.log 
          echo "ERROR: Authentication failure" > logs/app2.log
          echo "ERROR: process failed" >> logs/app2.log

      - name: Make script executable
        run: chmod +x scripts/log_summary.sh

      - name: Run script
        run: ./scripts/log_summary.sh logs
